version: 0.2

phases:
  install:
    runtime-versions:  
      java: corretto17 # https://docs.aws.amazon.com/codebuild/latest/userguide/runtime-versions.html
    pre_build:
      commands:
        - echo Nothing to do in this phase
    build:
      commands:
        - echo Build started on `date`
        - mvn clean install
    post_build:
      commands:
        - echo Build completed on `date`


artifacts:
  files:
    - target/**/*.jar
  discard-paths: yes
