version: 0.2

phases:
  install:
    runtime-versions: 
      java: corretto17
    pre_build:
      commands:
        - echo Nothing to do in this phase
    build:
      commands:
        - echo Build started on `date`
        - mvn clean install
    post_build:
      commands:
        - echoo Build completed on `date`


artifacts:
  files:
    - target/**/*.jar
  discard-paths: yes
